"""empty message

Revision ID: 0c82c4597641
Revises: 7f521ff34302
Create Date: 2025-12-31 15:43:55.853562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c82c4597641'
down_revision = '7f521ff34302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('MODERATION', 'PUBLISHED', 'ARCHIVED', 'DELETED'), server_default=sa.text("'MODERATION'"), nullable=False))

    # ### end Alembic commands ###
