"""add new post status

Revision ID: 5fc35b944f00
Revises: 0c82c4597641
Create Date: 2025-12-31 15:44:48.403708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc35b944f00'
down_revision = '0c82c4597641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'MODERATION', 'PUBLISHED', 'ARCHIVED', 'DELETED', name='post_status_enum'), server_default='draft', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
