"""add table posts

Revision ID: 689d17a3309e
Revises: fc610c96f3e0
Create Date: 2025-12-31 14:54:31.810543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689d17a3309e'
down_revision = 'fc610c96f3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('MODERATION', 'PUBLISHED', 'ARCHIVED', 'DELETED', name='post_status_enum'), server_default='moderation', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
