"""add column slug for posts

Revision ID: 7f521ff34302
Revises: 689d17a3309e
Create Date: 2025-12-31 15:32:35.564046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f521ff34302'
down_revision = '689d17a3309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_posts_slug'), ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_posts_slug'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
